version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: multi_gateway_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: multi_gateway
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - multi_gateway_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: multi_gateway_app
    restart: always
    depends_on:
      - mysql
    ports:
      - "3333:3333"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - multi_gateway_network
    environment:
      - PORT=3333
      - HOST=0.0.0.0
      - NODE_ENV=development
      - APP_KEY=your-app-key-here-32-chars-length
      - DRIVE_DISK=local
      - DB_CONNECTION=mysql
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DB_NAME=multi_gateway
      - GATEWAY1_URL=http://gateway1:3001
      - GATEWAY2_URL=http://gateway2:3002
      - GATEWAY1_EMAIL=dev@betalent.tech
      - GATEWAY1_TOKEN=FEC9BB078BF338F464F96B48089EB498
      - GATEWAY2_AUTH_TOKEN=tk_f2198cc671b5289fa856
      - GATEWAY2_AUTH_SECRET=3d15e8ed6131446ea7e3456728b1211f

  gateway1:
    image: matheusprotzen/gateways-mock
    container_name: gateway1
    networks:
      - multi_gateway_network
    ports:
      - "3001:3001"

  gateway2:
    image: matheusprotzen/gateways-mock
    container_name: gateway2
    networks:
      - multi_gateway_network
    ports:
      - "3002:3002"

networks:
  multi_gateway_network:
    driver: bridge

volumes:
  mysql_data:
